<?php
/**
 * @file
 * Define the database schema and update functions for the database server module.
 */

/**
 * Implements hook_schema().
 */
function hosting_db_server_schema() {
  $schema['hosting_db_server'] = array(
    'fields' => array(
      'server_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'db_user' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'db_passwd' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('server_id'),
  );

  return $schema;
}

