<?php

/**
 * @file
 * Module code for Hosting task garbage collection
 */

/**
 * Implements hook_hosting_queues().
 *
 * Return a list of queues that this module needs to manage.
 */
function hosting_task_gc_hosting_queues() {
  $count = hosting_task_gc_count_sites();
  $queue['task_gc'] = array(
    'name' => t('Task GC'),
    'description' => t('Process the garbage collection of task logs.'),
    // Run queue sequentially. always with the same parameters.
    'type' => HOSTING_QUEUE_TYPE_BATCH,
    'frequency' => strtotime("1 hour", 0),
    'items' => 20,
    'total_items' => $count,
    'min_threads' => 6,
    'max_threads' => 12,
    'threshold' => 100,
    'singular' => t('site'),
    'plural' => t('sites'),
  );
  return $queue;
}

/**
 * The main queue callback task_gc.
 */
function hosting_task_gc_queue() {
  // Switch to the super user.
  $account_switcher = \Drupal::service('account_switcher');
  $admin = \Drupal::entityTypeManager()->getStorage('user')->load(1);
  if ($admin) {
    $account_switcher->switchTo($admin);
  }

  $result = hosting_task_gc_list_sites();
  while ($site = $result->fetchObject()) {
    $query = "SELECT id FROM {hosting_task} WHERE rid = :rid";
    $tasks_to_remove = \Drupal::database()->query($query, array(':rid' => $site->id));
    while ($row = $tasks_to_remove->fetchObject()) {
      $task = \Drupal::entityTypeManager()->getStorage('hosting_task')->load($row->id);
      if ($task) {
        $task->delete();
      }
      \Drupal::logger('hosting_task_gc')->notice('Deleted task entity with id @id.', ['@id' => $row->id]);
    }
  }

  // Restore the user.
  if ($admin) {
    $account_switcher->switchBack();
  }
  // Look for orphaned task log entries.
  $query = "SELECT DISTINCT h.task_id
              FROM {hosting_task_log} h
                LEFT OUTER JOIN {hosting_task} t ON h.task_id = t.id
              WHERE t.id IS NULL LIMIT 100";
  $result = \Drupal::database()->query($query);
  while ($revision = $result->fetchObject()) {
    $num = \Drupal::database()->delete('hosting_task_log')
      ->condition('task_id', $revision->task_id)
      ->execute();
    \Drupal::logger('hosting_task_gc')->notice('Deleted @num orphaned task log entries with task_id @task_id.', ['@num' => $num, '@task_id' => $revision->task_id]);
  }
}

/**
 * Prepare a list of sites with garbage to collect.
 *
 * @return DatabaseStatementInterface
 *   A result object.
 */
function hosting_task_gc_list_sites() {
  $query = "SELECT DISTINCT s.id "
          . "FROM {hosting_site} s INNER JOIN {hosting_task} t ON s.id = t.rid "
          . "WHERE s.status = :status LIMIT 5";
  return \Drupal::database()->query($query, array(':status' => HOSTING_SITE_DELETED));
}

/**
 * Get the number of sites with garbage to collect.
 *
 * @return int
 *   The number of sites.
 */
function hosting_task_gc_count_sites() {
  // This query can be super expensive to run, so only run it once every hour.
  if ($cache = \Drupal::cache()->get(__FUNCTION__)) {
    return $cache->data;
  }
  else {
    $query = "SELECT COUNT(DISTINCT s.id) AS num_sites "
      . "FROM {hosting_site} s INNER JOIN {hosting_task} t ON s.id = t.rid "
      . "WHERE s.status = :status";
    $result = \Drupal::database()->query($query, array(':status' => HOSTING_SITE_DELETED))->fetchField();
    \Drupal::cache()->set(__FUNCTION__, $result, REQUEST_TIME + 3600);
    return $result;
  }
}

/**
 * Implements hook_node_update().
 */
function hosting_task_gc_node_update($node) {
  if ($node->type == "site") {
    if (isset($node->site_status) && $node->site_status == HOSTING_SITE_DELETED) {
      \Drupal::cache()->delete('hosting_task_gc_count_sites');
    }
  }
}
