<?php
/**
 * @file
 *   Database schemas and update functions for the hosting_subdirs module.
 */

/**
 * Implements hook_install().
 */
function hosting_subdirs_install() {
  // Get the weight of the hosting_site module.
  $result = \Drupal::database()->select('system', 's')
              ->fields('s', array('weight'))
              ->condition('name', 'hosting_site', '=')
              ->execute();
  $weight = !empty($result) ? $result->fetchField() : 0;

  // Set our module to run before hosting_site.
  // @see: hosting_subdirs_node_presave().
  \Drupal::database()->update('system')
    ->fields(array('weight' => $weight - 1))
    ->condition('name', 'hosting_subdirs', '=')
    ->execute();
}


