<?php
/**
 * @file
 * Define the database schema and update functions for the hosting_task module.
 */

/**
 * Implements hook_schema().
 */
function hosting_task_schema() {
  $schema['hosting_task_arguments'] = array(
    'fields' => array(
      'task_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'name' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'value' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
    ),
    'indexes' => array(
      'task_id' => array('task_id'),
    ),
  );

  $schema['hosting_task_log'] = array(
    'fields' => array(
      'lid' => array(
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'task_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'type' => array(
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
        'default' => '',
      ),
      'message' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'error' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ),
      'timestamp' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'indexes' => array(
      'type' => array('type'),
      'task_id_lid' => array('task_id', 'lid'),
    ),
    'primary key' => array('lid'),
  );

  return $schema;
}

/**
 * Implements hook_install().
 */
function hosting_task_install() {
  hosting_install_view_configs('hosting_task');
}

/**
 * Implements hook_uninstall().
 */
function hosting_task_uninstall() {
  \Drupal::configFactory()->getEditable('hosting_task.settings')->delete();

  $entity_type_manager = \Drupal::entityTypeManager();
  if ($entity_type_manager->hasDefinition('node_type')) {
    $storage = $entity_type_manager->getStorage('node_type');
    if ($type = $storage->load('task')) {
      $type->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('view')) {
    $storage = $entity_type_manager->getStorage('view');
    if ($view = $storage->load('hosting_task_list')) {
      $view->delete();
    }
  }
}
