<?php
/**
 * @file
 * Define database schema for the hosting_web_cluster module.
 *
 */

/**
 * Implements hook_schema().
 */
function hosting_web_cluster_schema() {
  return array(
    'hosting_web_cluster' => array(
      'fields' => array(
        'server_id' => array(
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => TRUE,
          'default' => 0,
        ),
        'web_server_id' => array(
          'type' => 'int',
          'unsigned' => TRUE,
          'not null' => TRUE,
          'default' => 0,
        ),
      ),
      'primary key' => array('server_id', 'web_server_id'),
    ),
  );
}
