<?php
/**
 * @file
 * Define database schema and update functions for the hosting_site module.
 *
 */

/**
 * Implements hook_schema().
 */
function hosting_site_schema() {
  $schema['hosting_site_backups'] = array(
    'fields' => array(
      'bid' => array(
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'site' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'web_server' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'description' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'filename' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'size' => array(
        'type' => 'int',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'timestamp' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
    'primary key' => array('bid'),
  );

  return $schema;
}

/**
 * Implements hook_install().
 */
function hosting_site_install() {
  hosting_install_view_configs('hosting_site');
  hosting_install_form_display_configs('hosting_site');
  hosting_install_action_configs('hosting_site');
}

/**
 * Implements hook_uninstall().
 */
function hosting_site_uninstall() {
  \Drupal::configFactory()->getEditable('hosting_site.settings')->delete();

  $entity_type_manager = \Drupal::entityTypeManager();
  if ($entity_type_manager->hasDefinition('action')) {
    $storage = $entity_type_manager->getStorage('action');
    foreach ([
      'hosting_site_backup_action',
      'hosting_site_verify_action',
      'hosting_site_disable_action',
      'hosting_site_enable_action',
      'hosting_site_delete_action',
    ] as $action_id) {
      if ($action = $storage->load($action_id)) {
        $action->delete();
      }
    }
  }
  if ($entity_type_manager->hasDefinition('node_type')) {
    $storage = $entity_type_manager->getStorage('node_type');
    if ($type = $storage->load('site')) {
      $type->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('view')) {
    $storage = $entity_type_manager->getStorage('view');
    if ($view = $storage->load('hosting_site_list')) {
      $view->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('entity_form_display')) {
    $storage = $entity_type_manager->getStorage('entity_form_display');
    if ($display = $storage->load('hosting_site.hosting_site.default')) {
      $display->delete();
    }
  }
}
