hosting_client.settings:
  type: config_object
  label: 'Hosting client settings'
  mapping:
    hosting_client_prefix:
      type: string
      label: 'Client prefix'
    hosting_client_register_user:
      type: boolean
      label: 'Register user with client creation'
    hosting_client_require_client_to_create_site:
      type: boolean
      label: 'Require client before creating site'
    hosting_client_send_welcome:
      type: boolean
      label: 'Send welcome email'
    hosting_client_mail:
      type: mapping
      label: 'Client mail overrides'
      mapping:
        '*':
          type: string
