<?php
/**
 * @file
 * Allow the hosting system to cron all the installed sites on a schedule.
 */

/**
 * Implements hook_hosting_queues().
 *
 * @todo: In Hosting 4.x change the type to HOSTING_QUEUE_TYPE_SPREAD.
 */
function hosting_cron_hosting_queues() {
  $items['cron'] = array(
    'type' => HOSTING_QUEUE_TYPE_BATCH,
    'name' => t('Cron queue'),
    'description' => t('Run cron on hosted sites.'),
    'total_items' => hosting_site_count(),
    'frequency' => strtotime("1 hour", 0),
    'min_threads' => 6,
    'max_threads' => 12,
    'threshold' => 100,
    'singular' => t('site'),
    'plural' => t('sites'),
  );
  return $items;
}

/**
 * Implements hosting_QUEUE_TYPE_queue().
 */
function hosting_cron_queue($count) {
  $site_ids = \Drupal::entityTypeManager()->getStorage('hosting_site')->getQuery()
    ->condition('status', HOSTING_SITE_ENABLED)
    ->sort('last_cron', 'ASC')
    ->sort('id', 'ASC')
    ->range(0, $count)
    ->execute();

  $i = 0;
  foreach ($site_ids as $site_id) {
    if ($i >= $count) {
      break;
    }
    $site = \Drupal::entityTypeManager()->getStorage('hosting_site')->load($site_id);
    if (!$site) {
      continue;
    }
    $site_name = hosting_context_name($site->id());

  if (\Drupal::config('hosting.settings')->get('hosting_cron_use_backend') ?? TRUE) {
      provision_backend_invoke($site_name, "cron");
    }
    else {
      $drush_result = provision_backend_invoke($site_name, 'core-status', array('drupal-version'), array('--pipe'));
      if ($drush_result['error_status'] === 0) {
        $core_status = json_decode(trim($drush_result['output']), TRUE);
        if (!empty($core_status['drupal-version'])) {
          $version = explode('.', $core_status['drupal-version']);
          $major_version = array_shift($version);
        }
      }
      if (!empty($major_version) && $major_version >= 8) {
        $url = _hosting_site_url($site) . '/cron';
        if (!empty($site->get('cron_key')->value)) {
          $url .= '/' . rawurlencode($site->get('cron_key')->value);
        }
      }
      else {
        // Optionally add the cron_key querystring key if the site has one.
        $url = _hosting_site_url($site) . '/cron.php';
        if (!empty($site->get('cron_key')->value)) {
          $url .= '?cron_key=' . rawurlencode($site->get('cron_key')->value);
        }
      }
      hosting_log(t('running cron on URL @url', ['@url' => $url]), 'notice', [], 'hosting_cron');
      $error = '';
      try {
        \Drupal::httpClient()->request('GET', $url, array('timeout' => 30));
      }
      catch (\Exception $e) {
        $error = $e->getMessage();
      }
      if ($error) {
        \Drupal::logger('hosting_cron')->notice('cron failed on site %site with error %error', ['%site' => $site->label(), '%error' => $error]);
        continue; // don't update the timestamp
      }
    }

    // We are updating the site table here directly to avoid a possible race condition,
    // with the task queue. There exists a chance that they might both try to save the
    // same node at the same time, and then an old record from the cron queue might
    // replace the newly updated record.
    \Drupal::database()->update('hosting_site')
      ->fields(array(
        'last_cron' => REQUEST_TIME,
      ))
      ->condition('id', $site->id())
      ->execute();
    $i++;
  }
}

/**
 * Implements hook_node_view().
 */
function hosting_cron_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'site') {
    if ($view_mode != 'teaser') {
      // @todo : turn it into x minutes ago
      $node->content['info']['last_cron'] = array(
        '#type' => 'item',
        '#title' => t('Cron run'),
        '#weight' => 20,
        '#markup' => hosting_format_interval($node->last_cron),
      );
    }
  }
}
