<?php
/**
 * @file
 * Define the database schema and update functions for the hosting_server module.
 *
 */

/**
 * Implements hook_schema().
 */
function hosting_server_schema() {
  $schema['hosting_ip_addresses'] = array(
    'fields' => array(
      'server_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'ip_address' => array(
        'type' => 'text',
        'size' => 'small',
        'not null' => TRUE,
      ),
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array(
      'server_id' => array('server_id'),
    ),
  );

  $schema['hosting_service'] = array(
    'fields' => array(
      'server_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'service' => array(
        'type' => 'text',
        'size' => 'small',
        'not null' => TRUE,
      ),
      'type' => array(
        'type' => 'text',
        'size' => 'small',
        'not null' => TRUE,
      ),
      'restart_cmd' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'port' => array(
        'type' => 'int',
        'default' => 0,
        'unsigned' => TRUE,
        'not null' => FALSE,
      ),
      'available' => array(
        'type' => 'int',
        'size' => 'small',
        'not null' => TRUE,
        'default' => 1,
      ),
    ),
    'indexes' => array(
      'server_id' => array('server_id'),
    ),
  );

  return $schema;
}

/**
 * Implements hook_install().
 */
function hosting_server_install() {
  hosting_install_view_configs('hosting_server');
  hosting_install_form_display_configs('hosting_server');
}

/**
 * Implements hook_uninstall().
 */
function hosting_server_uninstall() {
  \Drupal::configFactory()->getEditable('hosting_server.settings')->delete();

  $entity_type_manager = \Drupal::entityTypeManager();
  if ($entity_type_manager->hasDefinition('node_type')) {
    $storage = $entity_type_manager->getStorage('node_type');
    if ($type = $storage->load('server')) {
      $type->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('view')) {
    $storage = $entity_type_manager->getStorage('view');
    if ($view = $storage->load('hosting_server_list')) {
      $view->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('entity_form_display')) {
    $storage = $entity_type_manager->getStorage('entity_form_display');
    if ($display = $storage->load('hosting_server.hosting_server.default')) {
      $display->delete();
    }
  }
}



/**
 * Implements hook_update_N().
 *
 * Cleanup site-specific IP mappings.
 *
 * Those are now associated only to servers again, and different modules
 * should manage their own mappings.
 *
 * @todo enable this in 3.x? or maybe after the RC cycle of 2.x? we keep the
 * data right now because the above request is quite error-prone and we are
 * not sure we cover all cases.
 */
/* function hosting_server_update_6203() { */
/*   $ret = array(); */
/*   $ret[] = update_sql("DELETE {hosting_ip_addresses} FROM {hosting_ip_addresses} LEFT JOIN {hosting_server} ON hosting_ip_addresses.server_id = hosting_server.id WHERE hosting_server.id IS NULL;"); */
/*   return $ret; */
/* } */
