<?php
/**
 * @file
 * The hosting server data example.
 */

/**
 * Implements hook_form_alter().
 */
function hosting_server_data_form_alter(&$form, $form_state, $form_id) {
  if (!in_array($form_id, array('hosting_server_form', 'hosting_server_add_form', 'hosting_server_edit_form'), TRUE)) {
    return;
  }

  $entity = NULL;
  if (isset($form['#entity'])) {
    $entity = $form['#entity'];
  }
  elseif (isset($form['#node'])) {
    $entity = $form['#node'];
  }

  $form['server_data'] = array(
    '#type' => 'fieldset',
    '#title' => t('Server data example'),
    '#description' => t('Example implementation of saving data into the server context.'),
  );

  $form['server_data']['server_data'] = array(
    '#type' => 'textfield',
    '#title' => t('Server data'),
    '#default_value' => ($entity && isset($entity->server_data)) ? $entity->server_data : '',
    '#weight' => 0,
  );
}

/**
 * Implements hook_hosting_server_insert().
 */
function hosting_server_data_hosting_server_insert($entity) {
  $server_id = hosting_entity_id($entity);
  if ($server_id && !empty($entity->server_data)) {
    \Drupal::database()->insert('hosting_server_data')->fields(array(
      'server_id' => $server_id,
      'server_data' => $entity->server_data,
    ))
    ->execute();
  }
}

/**
 * Implements hook_hosting_server_update().
 */
function hosting_server_data_hosting_server_update($entity) {
  $server_id = hosting_entity_id($entity);
  if (!$server_id) {
    return;
  }

  if (FALSE === \Drupal::database()->query("SELECT server_data FROM {hosting_server_data} WHERE server_id = :server_id", array(':server_id' => $server_id))->fetchField()) {
    hosting_server_data_hosting_server_insert($entity);
  }
  else {
    \Drupal::database()->update('hosting_server_data')
      ->fields(array(
        'server_data' => $entity->server_data,
      ))
      ->condition('server_id', $server_id)
      ->execute();
  }
}

/**
 * Implements hook_hosting_server_load().
 */
function hosting_server_data_hosting_server_load($entities) {
  foreach ($entities as $entity_id => $entity) {
    $server_id = hosting_entity_id($entity);
    if ($server_id) {
      $entities[$entity_id]->server_data = \Drupal::database()->query("SELECT server_data FROM {hosting_server_data} WHERE server_id = :server_id", array(':server_id' => $server_id))->fetchField();
    }
  }
}

/**
 * Implements hook_hosting_server_delete().
 */
function hosting_server_data_hosting_server_delete($entity) {
  $server_id = hosting_entity_id($entity);
  if ($server_id) {
    \Drupal::database()->delete('hosting_server_data')
      ->condition('server_id', $server_id)
      ->execute();
  }
}

/**
 * Implements hook_hosting_server_context_options().
 */
function hosting_server_data_hosting_server_context_options(&$task) {
  if (isset($task->ref->server_data) && !empty($task->ref->server_data)) {
    $task->context_options['server_data'] = $task->ref->server_data;
  }
  else {
    $task->context_options['server_data'] = 'null';
  }
}

/**
 * Implements hook_drush_context_import().
 */
function hosting_server_data_drush_context_import($context, &$node) {
  if ($context->type == 'server') {
    if (isset($context->server_data) && !empty($context->server_data)) {
      $node->server_data = $context->server_data;
    }
  }
}

/**
 * Register our directory as a place to find provision classes.
 */
function server_data_provision_register_autoload() {
  static $loaded = FALSE;
  if (!$loaded) {
    $loaded = TRUE;
    provision_autoload_register_prefix('Provision_', dirname(__FILE__) . '/drush');
  }
}

/**
 * Implements hook_provision_services().
 *
 * Expose the service type this extension defines to provision.
 *
 * @return array
 *   An array with the service type as key, and the default implementation the value.
 */
function server_data_provision_services() {
  server_data_provision_register_autoload();
  return array('server_data' => NULL);
}
