<?php
/**
 * @file
 * Install, update and uninstall functions for the hosting_server_data module.
 */


/**
 * Implements hook_schema().
 */
function hosting_server_data_schema() {
  $schema['hosting_server_data'] = array(
    'fields' => array(
      'server_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'server_data' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
      ),
    ),
    'indexes' => array(
      'server_id' => array('server_id'),
    ),
  );

  return $schema;
}
