<?php
/**
 * @file
 * Define database schema and update functions for the Platforms module.
 */

/**
 * Implements hook_schema().
 */
function hosting_platform_schema() {
  return [];
}

/**
 * Implements hook_install().
 */
function hosting_platform_install() {
  hosting_install_view_configs('hosting_platform');
  hosting_install_form_display_configs('hosting_platform');
  hosting_install_action_configs('hosting_platform');
}

/**
 * Implements hook_uninstall().
 */
function hosting_platform_uninstall() {
  \Drupal::configFactory()->getEditable('hosting_platform.settings')->delete();

  $entity_type_manager = \Drupal::entityTypeManager();
  if ($entity_type_manager->hasDefinition('action')) {
    $storage = $entity_type_manager->getStorage('action');
    foreach ([
      'hosting_platform_verify_action',
      'hosting_platform_lock_action',
      'hosting_platform_unlock_action',
      'hosting_platform_delete_action',
    ] as $action_id) {
      if ($action = $storage->load($action_id)) {
        $action->delete();
      }
    }
  }
  if ($entity_type_manager->hasDefinition('node_type')) {
    $storage = $entity_type_manager->getStorage('node_type');
    if ($type = $storage->load('platform')) {
      $type->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('view')) {
    $storage = $entity_type_manager->getStorage('view');
    if ($view = $storage->load('hosting_platform_list')) {
      $view->delete();
    }
  }
  if ($entity_type_manager->hasDefinition('entity_form_display')) {
    $storage = $entity_type_manager->getStorage('entity_form_display');
    if ($display = $storage->load('hosting_platform.hosting_platform.default')) {
      $display->delete();
    }
  }
}
