<?php
/**
 * @file
 * Define database schema and update function for the site aliases module.
 */

/**
 * Implements hook_schema().
 */
function hosting_alias_schema() {
  $schema['hosting_site_alias'] = array(
    'fields' => array(
      'site_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'alias' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
      ),
      'automatic' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'redirection' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
    ),
    'indexes' => array(
      'site_id' => array('site_id'),
      'alias' => array('alias'),
    ),
  );

  return $schema;
}

