<?php
/**
 * @file
 * Install, update and uninstall functions for the hosting_queued module.
 *
 */


/**
 * Implements hook_enable().
 */
function hosting_queued_enable() {
  // Disable Aegir's dispatch of the tasks queue.
  \Drupal::state()->set('hosting_queue_tasks_enabled', FALSE);

  // Disable the predecessor of this module from the Aegir 1.x world
  \Drupal::service('module_installer')->uninstall(array('hosting_queue_runner'));
}

/**
 * Implements hook_disable().
 */
function hosting_queued_disable() {
  // Enable Aegir's dispatch of the tasks queue.
  \Drupal::state()->set('hosting_queue_tasks_enabled', TRUE);
}

/**
 * Implements hook_uninstall().
 */
function hosting_queued_uninstall() {
  \Drupal::configFactory()->getEditable('hosting_queued.settings')->delete();
}
