<?php
/**
 * @file
 * Define database schema and update functions for the package management module.
 */

/**
 * Implements hook_schema().
 */
function hosting_package_schema() {
  $schema['hosting_package_instance'] = array(
    'fields' => array(
      'iid' => array(
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'rid' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'package_id' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'filename' => array(
        'type' => 'text',
        'size' => 'normal',
        'not null' => TRUE,
      ),
      'schema_version' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'version' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'version_code' => array(
        'type' => 'int',
        'size' => 'big',
        'not null' => TRUE,
        'default' => 0,
      ),
      'status' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
      'platform' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('iid'),
    'indexes' => array(
      'hosting_package_rid_idx' => array('rid'),
      'hosting_package_id_idx' => array('package_id'),
    ),
  );

  $schema['hosting_package_languages'] = array(
    'fields' => array(
      'iid' => array(
        'type' => 'int',
        'not null' => TRUE,
      ),
      'language' => array(
        'type' => 'varchar',
        'length' => 12,
        'not null' => TRUE,
        'default' => '',
      ),
    ),
  );

  return $schema;
}


